In [37]:
#import library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [38]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [39]:
print(X)

[['Jakarta' 40.0 4416186.0]
 ['Semarang' 30.0 2810025.0]
 ['Denpasar' 30.0 2494000.0]
 ['Jakarta' nan 2013810.0]
 ['Semarang' 40.0 4300470.0]
 ['Denpasar' 39.0 3742276.0]
 ['Jakarta' 30.0 2069530.0]
 ['Semarang' 28.0 4782935.0]
 ['Denpasar' 39.0 4798312.0]
 ['Jakarta' 35.0 nan]]


In [40]:
print(Y)

['Yes;;' 'No;;' 'No;;' 'Yes;;' 'No;;' 'Yes;;' 'No;;' 'Yes;;' 'No;;'
 'Yes;;']


In [41]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [43]:
print(X)

[['Jakarta' 40.0 4416186.0]
 ['Semarang' 30.0 2810025.0]
 ['Denpasar' 30.0 2494000.0]
 ['Jakarta' 34.55555555555556 2013810.0]
 ['Semarang' 40.0 4300470.0]
 ['Denpasar' 39.0 3742276.0]
 ['Jakarta' 30.0 2069530.0]
 ['Semarang' 28.0 4782935.0]
 ['Denpasar' 39.0 4798312.0]
 ['Jakarta' 35.0 3491949.3333333335]]


In [46]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [47]:
print(X)

[[0.0 1.0 0.0 40.0 4416186.0]
 [0.0 0.0 1.0 30.0 2810025.0]
 [1.0 0.0 0.0 30.0 2494000.0]
 [0.0 1.0 0.0 34.55555555555556 2013810.0]
 [0.0 0.0 1.0 40.0 4300470.0]
 [1.0 0.0 0.0 39.0 3742276.0]
 [0.0 1.0 0.0 30.0 2069530.0]
 [0.0 0.0 1.0 28.0 4782935.0]
 [1.0 0.0 0.0 39.0 4798312.0]
 [0.0 1.0 0.0 35.0 3491949.3333333335]]


In [48]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [49]:
print(Y)

[1 0 0 1 0 1 0 1 0 1]


In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state = 1)

In [54]:
print(X_train)

[[0.0 1.0 0.0 30.0 2069530.0]
 [0.0 0.0 1.0 40.0 4300470.0]
 [0.0 1.0 0.0 40.0 4416186.0]
 [0.0 1.0 0.0 34.55555555555556 2013810.0]
 [0.0 0.0 1.0 30.0 2810025.0]
 [0.0 0.0 1.0 28.0 4782935.0]
 [1.0 0.0 0.0 39.0 4798312.0]
 [1.0 0.0 0.0 39.0 3742276.0]]


In [55]:
print(X_test)

[[1.0 0.0 0.0 30.0 2494000.0]
 [0.0 1.0 0.0 35.0 3491949.3333333335]]


In [56]:
print(Y_train)

[0 0 1 1 0 1 0 1]


In [57]:
print(Y_test)

[0 1]


In [59]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [60]:
print(X_train)

[[0.0 1.0 0.0 -1.0653086744778615 -1.4203337484460457]
 [0.0 0.0 1.0 1.0361221354510715 0.6277241308842001]
 [0.0 1.0 0.0 1.0361221354510715 0.7339542695542579]
 [0.0 1.0 0.0 -0.10799019439912505 -1.4714860811113262]
 [0.0 0.0 1.0 -1.0653086744778615 -0.7405410963107796]
 [0.0 0.0 1.0 -1.485594836463648 1.07063888643615]
 [1.0 0.0 0.0 0.8259790544581781 1.084755351249395]
 [1.0 0.0 0.0 0.8259790544581781 0.11528828774414832]]


In [61]:
print(X_test)

[[1.0 0.0 0.0 -1.0653086744778615 -1.030659831604127]
 [0.0 1.0 0.0 -0.014593269513395036 -0.1145177590671251]]
